---
apiVersion: v1
kind: Service
metadata:
  name: fiap-postech-selfservice-fastfood-public-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: fiap-postech-selfservice-fastfood
  ports:
    - protocol: TCP
      port: 8000
      targetPort: web
